/* auto-generated by Haiku research agents — per-mushroom enrichment for chefs/controleurs/nerds modes */
const EXTRAS = {
 "1": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — bitter anticoagulant resin."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 4,
   "bonus": "Atromentin is being researched as a blood thinner; it's one of few naturally-occurring anticoagulants."
  }
 },
 "2": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 10,
   "remedy": "EMERGENCY: Call poison control; IV fluid therapy and silibinin required; organ damage irreversible if untreated."
  },
  "nerd": {
   "score": 10,
   "bonus": "The two-stage poison cycle tricks victims: symptoms vanish before organ damage becomes catastrophic."
  }
 },
 "3": {
  "chef": {
   "score": 10,
   "tip": "Shave thin over warm pasta or eggs for umami complexity."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Cannot be cultured; wild mycorrhizal partners required. Entire French Périgord economy depends on it."
  }
 },
 "4": {
  "chef": {
   "score": 9,
   "tip": "Sauté in butter; pairs perfectly with cream and eggs."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "The false gills are actually ridges—true gills would indicate a toxic Jack-O'-Lantern lookalike."
  }
 },
 "5": {
  "chef": {
   "score": 5,
   "tip": "Must be cooked; mild nutty flavor in stews."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Azulene pigments are rare in fungi; this is the Americas' only naturally blue milk cap."
  }
 },
 "6": {
  "chef": {
   "score": 3,
   "tip": "Edible but thin-fleshed; use as garnish."
  },
  "controleur": {
   "score": 1,
   "remedy": "No toxin risk; bioaccumulates arsenic (100+ mg/kg)—avoid frequent consumption from polluted sites."
  },
  "nerd": {
   "score": 6,
   "bonus": "Arsenic hyperaccumulation mechanism is still poorly understood by mycologists."
  }
 },
 "7": {
  "chef": {
   "score": 6,
   "tip": "Fry crispy for bacon-like umami."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Enzyme cocktails evolved to break down petroleum; now used in bioremediation research."
  }
 },
 "8": {
  "chef": {
   "score": 2,
   "tip": "Too slimy and small; not worthwhile."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Color shifts from green to pink occur as anthocyanin and carotenoid ratios change with age."
  }
 },
 "9": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — inedible despite beauty."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Its vibrant blue comes from rare anthraquinone pigments; appears on NZ currency as national symbol."
  }
 },
 "10": {
  "chef": {
   "score": 8,
   "tip": "Sauté or roast; meaty texture works as poultry substitute."
  },
  "controleur": {
   "score": 1,
   "remedy": "Mild allergic reactions (~10%) possible (swollen lips, nausea); cook thoroughly only from safe hardwoods."
  },
  "nerd": {
   "score": 5,
   "bonus": "Parasitic wood-decay enzymes give its meat the texture of cooked poultry without cooking."
  }
 },
 "11": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — elusive rarity with unknown toxicity."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "The loud hiss release is from compressed spore clouds escaping dried perithecial valves."
  }
 },
 "12": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — deadly even when cooked."
  },
  "controleur": {
   "score": 10,
   "remedy": "EMERGENCY: Call poison control; activated charcoal within 1h, IV silibinin/penicillin G, liver-function monitoring."
  },
  "nerd": {
   "score": 10,
   "bonus": "Amatoxin α-amanitin inhibits RNA polymerase II at femtomolar concentrations—one of biology's most potent poisons."
  }
 },
 "13": {
  "chef": {
   "score": 7,
   "tip": "Dry for intense flavor; rehydrate for mushroom powder."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Ring expansion ~10–40 cm per year; oldest rings date back 500+ years in UK pastures."
  }
 },
 "14": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — underground symbiont."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 9,
   "bonus": "Plants fight via the network: one tree signals aphid attacks; partners mount chemical defenses."
  }
 },
 "15": {
  "chef": {
   "score": 7,
   "tip": "Excellent edible; sauté or use in stocks."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Huitlacoche has more lysine per gram than corn; Aztecs valued it before Spanish conquest."
  }
 },
 "16": {
  "chef": {
   "score": 10,
   "tip": "Slice thick and sear quickly; scent defines Japanese autumn."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Matsutake doesn't fruit until soil reaches specific temperature; harvest season razor-sharp, late autumn."
  }
 },
 "17": {
  "chef": {
   "score": 0,
   "tip": "Too rare and declining; protect, don't harvest."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Guttation droplets are blood-red due to atromentin (same as Hydnellum peckii, different genus)."
  }
 },
 "18": {
  "chef": {
   "score": 2,
   "tip": "Traditional medicinal tea for parasites."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Ötzi used it 5,300 years ago; modern studies confirm antiparasitic compounds; continuous human utility."
  }
 },
 "19": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — toxic despite being edible when old."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; boil thoroughly 10–15 min with water disposal destroys thermolabile toxins."
  },
  "nerd": {
   "score": 7,
   "bonus": "Bioluminescence caused by oxidation of fungal luciferin; happens when rhizomorphs are fresh-cut."
  }
 },
 "20": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — smells of carrion."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Darwin's daughter Etty campaigned against it because its form resembled male genitalia; Victorian prudery."
  }
 },
 "21": {
  "chef": {
   "score": 7,
   "tip": "Use immediately after picking; dissolves quickly."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Ink is made of spores dissolved in liquid ammonia; fungus self-digests (autolysis) into usable ink."
  }
 },
 "22": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — fatal like Death Cap."
  },
  "controleur": {
   "score": 10,
   "remedy": "EMERGENCY: Call poison control; silibinin and IV fluids required; amatoxin onset 6–24h."
  },
  "nerd": {
   "score": 7,
   "bonus": "Galerina has α-amanitin like Death Cap; confusion in foraging has caused fatalities."
  }
 },
 "23": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Seek medical attention if severe psychological distress; benzodiazepines for anxiety. WARNING: Galerina lookalikes are deadly—confirm spore print."
  },
  "nerd": {
   "score": 9,
   "bonus": "Psilocybin dephosphorylates to psilocin in stomach; modern trials show sustained remission in 70% depression cases."
  }
 },
 "24": {
  "chef": {
   "score": 10,
   "tip": "Shave raw over risotto or soft cheese—cooking destroys its magic."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 10,
   "bonus": "Tuber magnatum cannot reproduce outside its specific oak–hazel–soil partnership; fully unculturable."
  }
 },
 "25": {
  "chef": {
   "score": 6,
   "tip": "Invasive in North America; mild flavor, good for stir-fries."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Escaped from commercial kits in 1990s; now outcompetes native oyster species in several US states."
  }
 },
 "26": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — toxicity profile uncertain."
  },
  "controleur": {
   "score": 7,
   "remedy": "Seek medical attention; IV hydration — illudin toxins cause 24–48h GI illness."
  },
  "nerd": {
   "score": 8,
   "bonus": "Bioluminescence via oxyluciferin; Aboriginal Australian cultural naming predates European mycology by millennia."
  }
 },
 "27": {
  "chef": {
   "score": 7,
   "tip": "Rapid growth; prized in Asian haute cuisine."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "The indusium (lace skirt) can grow to 10 cm; unrolls at ~2 mm per minute in optimal conditions."
  }
 },
 "28": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — signals morel season, nothing more."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Ascospores released by rain-induced mechanical pressure; morel fruiting often follows within 2 weeks."
  }
 },
 "29": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — contains rocket-fuel components."
  },
  "controleur": {
   "score": 9,
   "remedy": "EMERGENCY: Call poison control; pyridoxine (IV B6) specific antidote; aggressive hydration and seizure management."
  },
  "nerd": {
   "score": 8,
   "bonus": "Gyromitrin converts to methylhydrazine in vivo; same ingredient in rocket fuel; dose-dependent toxicity."
  }
 },
 "30": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — inedible spore disperser."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Raindrops trigger a hydraulic spore-launch; puffing visible to naked eye; elegant biomechanics."
  }
 },
 "31": {
  "chef": {
   "score": 8,
   "tip": "Firmer flesh holds up to grilling; faint seafood notes."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Parasitic fungus (Hypomyces) completely reshapes host Russula; extreme example of mycoparasitism."
  }
 },
 "32": {
  "chef": {
   "score": 4,
   "tip": "Decent edible; cook thoroughly."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Mutations triggered by ethylene gas in farms; same mutation can affect entire harvests simultaneously."
  }
 },
 "33": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; mild GI upset — prevent by thorough cooking (parboil 10–15 min)."
  },
  "nerd": {
   "score": 10,
   "bonus": "The 'humongous fungus' is 2,400+ years old, 9.6 km², and ~13,600 tons—largest terrestrial organism by area."
  }
 },
 "34": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; mild GI upset — cook thoroughly to destroy thermolabile toxins."
  },
  "nerd": {
   "score": 7,
   "bonus": "Rhizomorphs glow via fungal luciferin; 'foxfire' stories in folklore likely describe this bioluminescence."
  }
 },
 "35": {
  "chef": {
   "score": 7,
   "tip": "Slice and pan-fry while young and white inside."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 9,
   "bonus": "7 trillion spores from one puffball; if each produced offspring, biomass would exceed Earth's mass in generations."
  }
 },
 "36": {
  "chef": {
   "score": 8,
   "tip": "Robust earthy flavor; perfect for dark broths and game."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "French name 'trompette de mort' is poetic but misleading—taste is delicate and prized, not fatal."
  }
 },
 "37": {
  "chef": {
   "score": 2,
   "tip": "Medicinal decoction; not a culinary ingredient."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 9,
   "bonus": "Polysaccharide-K (PSK/Krestin) approved in Japan, Korea, China; adjunct therapy shows 20% survival boost."
  }
 },
 "38": {
  "chef": {
   "score": 8,
   "tip": "Delicate; add to pasta or cream dishes at the last moment."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Camouflage so effective that field guides suggest looking for the 'hole' in the forest floor."
  }
 },
 "39": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — inedible spore sac."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Geastrum triplex (same species) appears multiple times; hygroscopic reactions lift spore sac as humidity rises."
  }
 },
 "40": {
  "chef": {
   "score": 2,
   "tip": "Steep as medicinal birch tea; not for eating."
  },
  "controleur": {
   "score": 1,
   "remedy": "No acute medical risk; avoid high-dose powder (>3g/day) long-term — kidney oxalate accumulation risk; avoid with anticoagulants."
  },
  "nerd": {
   "score": 7,
   "bonus": "Inonotus grows inside living birch; Siberians have traditionally harvested it for betulin-rich tea."
  }
 },
 "41": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — coral fungi are impossible to identify safely."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Coral fungi show extreme diversity; microscopy required to separate species; taxonomy still unsettled."
  }
 },
 "42": {
  "chef": {
   "score": 4,
   "tip": "Mild; good in mushroom mixtures."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Mycoparasitism: Chroogomphus hijacks Suillus mycelium; feeds on host without killing it (chronic parasitism)."
  }
 },
 "43": {
  "chef": {
   "score": 5,
   "tip": "Sour taste; better for dyeing wood than eating."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Brown oak heartwood is prized by luthiers; staining caused by Fistulina's dark pigment over years."
  }
 },
 "44": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — radioisotope accumulator."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 10,
   "bonus": "Radiosynthesis: melanin converts gamma radiation to chemical energy; tested as ISS shielding and Mars habitat cover."
  }
 },
 "45": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — causes severe poisoning."
  },
  "controleur": {
   "score": 7,
   "remedy": "Seek medical attention; IV hydration — documented fatalities from misidentification."
  },
  "nerd": {
   "score": 5,
   "bonus": "Bitterness is isoindole alkaloid; saves most victims; similar-looking Galerina has no warning taste."
  }
 },
 "46": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — biological herbicide."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Silver leaf disease caused by fungal toxins breaking vascular tissue; not a physiological change."
  }
 },
 "47": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — historical tinder, not food."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Daldinia's brittle sclerotia catch sparks; Fire-starting method used by foragers and ancient peoples."
  }
 },
 "48": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — common European poison."
  },
  "controleur": {
   "score": 7,
   "remedy": "Seek medical attention urgently; IV hydration and electrolyte management — one of Europe's most common poisonings."
  },
  "nerd": {
   "score": 6,
   "bonus": "Entoloma poisoning is muscarine-like; causes salivation, sweating, SLUDGE symptoms, but not organ failure."
  }
 },
 "49": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — glowing but inedible."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Bioluminescence so bright (in dim light) that Japanese folklore attributed it to foxfire spirits (kitsune)."
  }
 },
 "50": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — slow-fruiting & inedible."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Xylaria polymorpha releases ascospores over 6+ months; unusually protracted for ascomycetes."
  }
 },
 "51": {
  "chef": {
   "score": 1,
   "tip": "Not for the kitchen — natural canvas for wood-burning."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "White pore surface reacts with polyphenols (catechol oxidase); darkens permanently when scratched."
  }
 },
 "52": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — toxic with alcohol."
  },
  "controleur": {
   "score": 6,
   "remedy": "Seek medical attention; IV support 24–48h."
  },
  "nerd": {
   "score": 7,
   "bonus": "Coprine's disulfiram-like effect blocks aldehyde dehydrogenase; reaction can occur 72 hours post-consumption."
  }
 },
 "53": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — splash-cup disperser."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Splash-cup mechanism: raindrop energy launches spore masses (peridioles) up to 1 meter onto vegetation."
  }
 },
 "54": {
  "chef": {
   "score": 8,
   "tip": "Delicate; add to pasta or cream dishes at the last moment."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Black Trumpet is actually Craterellus (not Cantharellus); DNA showed it's a separate genus, not a lookalike."
  }
 },
 "55": {
  "chef": {
   "score": 2,
   "tip": "Technically edible but not worthwhile."
  },
  "controleur": {
   "score": 6,
   "remedy": "Seek medical attention; IV support 24–48h."
  },
  "nerd": {
   "score": 5,
   "bonus": "Verpa bohemica cap hangs freely; true morels (Morchella) are attached—simple but crucial distinction."
  }
 },
 "56": {
  "chef": {
   "score": 5,
   "tip": "Decent edible; cook thoroughly."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Some Suillus species concentrate radiocesium 100× soil level; used for Chernobyl/Fukushima bioremediation."
  }
 },
 "57": {
  "chef": {
   "score": 9,
   "tip": "Dry and powder for depth; rehydrate for risotto and sauces."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Boletus edulis shows global gene flow despite geographic separation; suggests ancient human spore transport."
  }
 },
 "58": {
  "chef": {
   "score": 1,
   "tip": "Historical bushcraft tinder; carries fire, not nourishment."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Fomitopsis pinicola wood ('punk') is hydrophobic and waterlogged; carried embers in fire-starting for millennia."
  }
 },
 "59": {
  "chef": {
   "score": 7,
   "tip": "Oyster variety; sauté in butter with garlic."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Heart-rot fungi create cavities; ecosystem engineers—woodpeckers, owls, bats wholly depend on fungal architecture."
  }
 },
 "60": {
  "chef": {
   "score": 8,
   "tip": "Sauté gently; studies suggest brain-health benefits."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Erinacine compounds stimulate NGF production; clinical trials show promise for Alzheimer's and nerve regeneration."
  }
 },
 "61": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — psychoactive and toxic."
  },
  "controleur": {
   "score": 6,
   "remedy": "Seek medical attention; IV support 24–48h."
  },
  "nerd": {
   "score": 8,
   "bonus": "Ibotenic acid (precursor to GABA) is neurotoxic; reindeer herds seek it for altered consciousness."
  }
 },
 "62": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — gelatinous folklore object."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Gelatinous texture from polysaccharides; 'witch's curse' folklore common in Germanic and British traditions."
  }
 },
 "63": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — lignin-degrader, not edible."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "White-rot fungi attack lignin via ligninase; Phellinus is a model for industrial wood breakdown studies."
  }
 },
 "64": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — toxic glowing fungus."
  },
  "controleur": {
   "score": 4,
   "remedy": "Supportive care with hydration — illudin toxins cause mild-moderate GI distress."
  },
  "nerd": {
   "score": 8,
   "bonus": "Regional bioluminescence variation unknown cause; North American strains glow, European don't—an unsolved mystery."
  }
 },
 "65": {
  "chef": {
   "score": 4,
   "tip": "Everyday workhorse; cook thoroughly."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 4,
   "bonus": "Agaricus bisporus is 90% of US market; cremini/portobello maturity variants; extreme monoculture dependency."
  }
 },
 "66": {
  "chef": {
   "score": 8,
   "tip": "Tender, absorbs flavors well; excellent in creamy dishes."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Sparassis crispa can persist at same root for decades; multi-year fruiting from single mycelial network."
  }
 },
 "67": {
  "chef": {
   "score": 5,
   "tip": "Texture-based ingredient for soups and desserts."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Tremella holds 500× its weight in water; used in TCM for 2,000+ years; hyaluronic-acid-like polymer composition."
  }
 },
 "68": {
  "chef": {
   "score": 5,
   "tip": "Remove sticky skin first; mild, good in stir-fries."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Suillus luteus hitchhiked with Pinus plantations globally; now invasive in NZ, Australia, South Africa."
  }
 },
 "69": {
  "chef": {
   "score": 8,
   "tip": "Slice stem thick and sear for \"scallop\" mimicry."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "King oyster's dense stem (vegan 'scallop') is mechanically strong due to pseudoparenchyma structure."
  }
 },
 "70": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — mimics edibles but is toxic."
  },
  "controleur": {
   "score": 6,
   "remedy": "Seek medical attention; IV support 24–48h."
  },
  "nerd": {
   "score": 5,
   "bonus": "Hebeloma crustuliniforme's radish smell is from sulfur compounds; guttation droplets visible on mature gills."
  }
 },
 "71": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — 23,000+ mating types but inedible."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 10,
   "bonus": "Schizophyllum's 23,000+ mating types possible due to multiple genetic loci; highest known sexual dimorphism."
  }
 },
 "72": {
  "chef": {
   "score": 6,
   "tip": "Best when fully white and firm; fry or grill."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Lycoperdon perlatum releases spores in discrete puffs; each raindrop impact visible to naked eye."
  }
 },
 "73": {
  "chef": {
   "score": 3,
   "tip": "Medicinal use as caterpillar fungus alternative."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Cordyceps militaris mummifies insect pupae; anamorph is Isaria; grown commercially as cheaper caterpillar-fungus alternative."
  }
 },
 "74": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — geometric but inedible."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Hexagonal pores are not machine-made; Neofavolus geometry optimizes spore dispersal and structural strength."
  }
 },
 "75": {
  "chef": {
   "score": 1,
   "tip": "Not for the kitchen — bruises black when touched."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; mild GI symptoms if raw."
  },
  "nerd": {
   "score": 6,
   "bonus": "Hygrocybe conica darkens jet-black due to melanin polymerization and protein oxidation after bruising."
  }
 },
 "76": {
  "chef": {
   "score": 2,
   "tip": "Medicinal decoction; not a culinary ingredient."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Trametes versicolor annual rings grow ~1–2 mm; easy to age; polyphores can live 15+ years."
  }
 },
 "77": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Mycelial networks are dominant biomass in temperate forest soils; collectively weigh more than all trees above."
  }
 },
 "78": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — lacks psilocybin despite appearance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; mild GI symptoms — often mistaken for psychoactive species."
  },
  "nerd": {
   "score": 5,
   "bonus": "Stropharia coronilla mistaken for psilocybes; contains no psilocybin, only gastrointestinal toxins."
  }
 },
 "79": {
  "chef": {
   "score": 7,
   "tip": "Large, elegant; batter and fry or roast whole."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Macrolepiota procera's movable ring is membranous and slides freely; unique diagnostic among large fungi."
  }
 },
 "80": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — bioindicator of ancient grassland."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Geoglossum is an ascomycete indicator of ancient, unimproved grassland; IUCN red-list conservation value."
  }
 },
 "81": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 10,
   "bonus": "Prototaxites grew 8+ meters tall in Devonian (430–360 Mya); tallest organisms before vascular plants evolved."
  }
 },
 "82": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Exidiopsis effusa ice-crystal formation prevented by secondary metabolites; antifreeze-like biochemistry."
  }
 },
 "83": {
  "chef": {
   "score": 10,
   "tip": "World-class delicacy; cook with minimal intervention."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Tuber magnatum cannot grow outside oak–hazel–calcareous-soil triangle; rarest and most expensive truffle."
  }
 },
 "84": {
  "chef": {
   "score": 7,
   "tip": "Rapid growth; prized in Asian haute cuisine."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Phallus indusiatus extends lace indusium at ~2 mm/min; among fastest-growing fungi; Chinese delicacy."
  }
 },
 "85": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Entoloma hochstetteri's three azulene pigments are rare in fungi; biochemical uniqueness matches rarity."
  }
 },
 "86": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — causes gastric distress."
  },
  "controleur": {
   "score": 6,
   "remedy": "Seek medical attention; IV support 24–48h."
  },
  "nerd": {
   "score": 5,
   "bonus": "Entoloma rhodopolium's pink gills age from white; muscarine toxin causes salivation and sweating."
  }
 },
 "87": {
  "chef": {
   "score": 2,
   "tip": "Technically edible but not worthwhile."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 5,
   "bonus": "Lycoperdon nigrescens spines detach as fruiting body matures; reveals net-like peridium beneath."
  }
 },
 "88": {
  "chef": {
   "score": 10,
   "tip": "World-class delicacy; cook with minimal intervention."
  },
  "controleur": {
   "score": 1,
   "remedy": "Cook thoroughly (raw morels contain hydrazine toxins); no risk when cooked."
  },
  "nerd": {
   "score": 8,
   "bonus": "Morchella esculenta contains gyromitrin (rocket fuel compound); raw morels genuinely toxic; cooking required."
  }
 },
 "89": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 7,
   "remedy": "Seek medical attention; IV hydration — illudin toxins cause 24–48h GI illness."
  },
  "nerd": {
   "score": 8,
   "bonus": "Omphalotus illudens bioluminescence via illudin; same compounds in clinical cancer trials (phase II)."
  }
 },
 "90": {
  "chef": {
   "score": 6,
   "tip": "Cultivated as enoki; delicate in soups and broths."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Flammulina velutipes grown as enoki in high-CO₂, darkness; cultivated aboard ISS—first fungi in space."
  }
 },
 "91": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Seek medical attention if severe psychological distress; benzodiazepines for anxiety. WARNING: Galerina lookalikes are deadly—confirm spore print."
  },
  "nerd": {
   "score": 8,
   "bonus": "'Golden Teacher' emerged in 1980s; now dominant psilocybin cultivar; genetics of origin strain unknown."
  }
 },
 "92": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 9,
   "bonus": "Rhizophagus irregularis forms reciprocal market: plants reward generous partners with extra carbon allocation."
  }
 },
 "93": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 9,
   "remedy": "EMERGENCY: Call poison control; liver/kidney damage risk; aggressive supportive care required."
  },
  "nerd": {
   "score": 8,
   "bonus": "Cryptococcus neoformans kills 100,000+ yearly (mostly immunocompromised); birds carry it asymptomatically."
  }
 },
 "94": {
  "chef": {
   "score": 7,
   "tip": "Rediscovered Sicilian delicacy; choice when available."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 8,
   "bonus": "Pleurotus nebrodensis thought extinct; rediscovered 1990s Sicily; IUCN formally protected—rare for fungi."
  }
 },
 "95": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — invasive and deadly."
  },
  "controleur": {
   "score": 10,
   "remedy": "EMERGENCY: Call poison control; activated charcoal within 1h, IV silibinin/penicillin G, liver-function monitoring."
  },
  "nerd": {
   "score": 8,
   "bonus": "California Death Caps reproduce unisexually via haploid cloning; single genotype spread across entire state."
  }
 },
 "96": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 7,
   "bonus": "Hydnellum peckii accumulates cesium-137; serves as biomarker for nuclear fallout in forest soil."
  }
 },
 "97": {
  "chef": {
   "score": 7,
   "tip": "Dry and powder for soups and sauces."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Marasmius oreades folklore blamed rings on fairies, witches, or dragons—premodern explanations for mycelial geometry."
  }
 },
 "98": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — lens cells create illusion, not food."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 6,
   "bonus": "Schistostega pennata's lens-shaped cells refract light; folklore 'goblin gold' is optical illusion, not bioluminescence."
  }
 },
 "99": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 3,
   "remedy": "Supportive care; mild GI symptoms if raw."
  },
  "nerd": {
   "score": 7,
   "bonus": "Hygrocybe conica's symbiotic partner unknown; likely cryptic biotrotrophy on mosses or grass—major unsolved mystery."
  }
 },
 "100": {
  "chef": {
   "score": 0,
   "tip": "Not for the kitchen — admire from a distance."
  },
  "controleur": {
   "score": 0,
   "remedy": "No medical risk."
  },
  "nerd": {
   "score": 10,
   "bonus": "Ophiocordyceps unilateralis doesn't invade ant brain; instead hijacks neurotransmitters; fungus remains in body."
  }
 }
};
